---
title: "Self Evaluation L01 Review"
subtitle: |
  | Data Science 2 with R 
  | STAT 301-2
author: "Ria Zaman"
pagetitle: "Self Evaluation PQ2 Ria Zaman"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false
  error: true

from: markdown+emoji
reference-location: margin
citation-location: margin 
---

::: {.callout-tip icon="false"}
## Github Repo Link

[Ria's Github Repo Link](https://github.com/stat301-3-2026-spring/l01-review-riazaman-1)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution
1. Collect and Clean Data: check for missingness, make sure data is tidy
2. Identify Features and Labels: identify target variables, conduct preliminary EDA to identify features or attributes that could impact the target variable
3. Split Data: split data into training and testing data. Resampling methods can also be implemented 
4. Train Model: Formulate recipes and feed the data through a supervised learning algorithm. Tuning parameters can also be explored here
5. Validate and Test Model: assess the model on new, unseen data and generate predictions to compare to the true values of the target variable. Performance metrics can be used here like accuracy or RMSE to determine effectiveness of the model
6. Analysis: analyze which model performed the best and why. Analyze the data and how this can be used for real world purposes

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation
I feel like we went over this a lot last quarter, so I remembered the steps very clearly. I combined a few of the steps written out in the solutions like collect and clean data, resampling and splitting, feature engineering and tuning, etc; however, I feel that my understanding was pretty much there and I didn't have to look anything up. 

:::

:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution
Supervised learning is task-driven and works with pre categorized data. It is commonly used for regression and classification problems, where the goal is to predict an outcome based on certain variables.

Unsupervised learning is data-driven and works with unlabeled data. It identifies underlying patterns or structures in the data, such as grouping observations into clusters without predefined categories.

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation
I felt quite confident answering this question because it directly tested a concept we covered a lot in class and quizzes last quarter. I think I was able to clearly recall the key differences between supervised and unsupervised learning and explain them concisely. 

:::

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution
Generally describe relationships or trends in the data. Linear and parametric models are often good for this. The goal is to summarize and understand patterns in the data, rather than make predictions or causal claims.

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution
These models aim to unpack the how and why of the inputs affect the target variable. They use data to understand how a variable influences another variable. These models are used to draw conclusions about a population and often involve statistical significance and hypothesis testing.

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution
Use data (predictors) to predict the outcome of a target variable. The focus is not so much understanding the how or why, but using data to try to predict the outcome as accurately as possible.

:::


### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation
I was pretty confident in answering these because I remembered them from last quarter and we also had a nice reminder of what they were with examples in class.  

:::


### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution
Mechanistic models explain why a system behaves a certain way using theories or known relationships. For example, a mechanistic model can predict how far a baseball will go as it follows the trajectory of a parabola and it can be understood using physics. They are based on assumptions about how the data is generated and focus on understanding the true process behind the data.


:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution
Empirically driven models rely on patterns found in the data rather than underlying theory. They use the data to learn relationships between variables, focusing on fitting the data well than explaining why those relationships exist.

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution
Mechanistic models are more likely parametric, which is based on the assumption that the data follows a known and predefined mathematical form or distribution. Empirically driven models are often nonparametric, which means they do not assume any fixed functional form. The model structure grows with the dataset, so nonparametric models are more flexible.


:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution
Mechanistic models are generally easier to interpret because they are based on known relationships/theories and have a clear structure. This makes it easier to understand how each input affects the output. Empirically driven models can be more complex and less transparent.


:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution
Mechanistic models are less flexible because they rely on predefined assumptions. Empirically driven models are more flexible since they adapt to patterns in the data and aren't confined to a fixed form.


:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution
Mechanistic models tend to have higher bias because they make strong assumptions but they have a lower variance. Empirical models tend to have lower bias but higher variance because can be more flexible.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation
I think these were okay. I was very confident answering all of the question except for the bias-variance trade-off. I feel like we talked about that only a little bit in class last quarter, so I definitely needed a refresher on what that was. 

:::


### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

Regression predicts continuous values using independent variables, such as predicting price of houses. 

Classification predicts categories by using a decision boundary to separate the data into the different classes. 


### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation
This was fine because we did a lot of regression and classification problems throughout winter quarter. 

:::

:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution
It makes sure that the training and testing sets maintain the same class proportion as the original dataset. This is important as it ensures the model trains on a accurately distributed dataset and it also leads to improved model accuracy. 


### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation
This was a good question and I was pretty confident when answering this. I think that this question tested our knowledge on the homework labs that we did last quarter; I could have elaborated on the consequences if the data is not distributed similarly in both datasets, such as leading to overfitting or underfitting, but I feel like I knew the content very well. 

:::

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

In v-fold cross validation, the data is split into v equal parts, which are called folds. The model is trained on v-1 folds and tested on the remaining fold. It is repeated until each fold acts as the testing fold, and if specified, the whole resampling method is repeated.  

V-fold cross validation is used because it provides a more reliable estimate of how the model would perform on new data and it reduces variability, while preventing overfitting to a particular training dataset. 

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation
I felt confident answering this question since I understood both the process and purpose of v-fold cross-validation with repeats. My answer covered the key idea of generating multiple out-of-sample RMSE estimates and averaging them for a more reliable measure of performance. While my solution was concise and correct, I could have included slightly more detail about the role of repeats in reducing variability.

:::

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

We might use a bootstrap resampling procedure instead of v-fold cross-validation when the dataset is small. In bootstrap sampling, we repeatedly sample with replacement from the dataset to create many training sets, allowing each observation to be used multiple times. It is also used when the population distribution is unknown, or when parametric assumptions (like normality) cannot be me. 

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation
I was less confident on this question since bootstrap resampling was not something we spent much time on last quarter. I remember speaking with my professor about it last quarter when discussing my final project, so I was able to recall the general idea and give a reasonable use case. I did need a refresher on what this was and my explanation lacked  confidence and depth compared to other topics.

:::

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution
Model tuning is the process of selecting the best values for a model’s hyperparameters by testing a range of values for each hyperparameter and evaluating different combinations.

Model tuning is used to improve the model’s performance by ensuring that the optimal hyperparameters are chosen. This helps reduce overfitting or underfitting.

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation
I felt pretty confident answering this because our professor last quarter really emphasized model tuning and understanding what goes on underneath the surface. I probably could've have given examples of hyperparameters that could be tuned such as learning rate, trees, min_n, but besides that I understood the content very well. 

:::

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution
RMSE, MAE
:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

Accuracy and ROC AUC
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation
Question 10 was definitely easy since we used these metrics every week last quarter. 
:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution
Inferential. We are trying to see if a higher number of service calls impacts a customer's likelihood of churn in the next month, hence the goal is to understand the relationship between these two variables. 

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution
Prediction. The goal here is to use the given data to predict the likelihood that a customer will churn in the next month. 

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation
I practiced a lot of these for the quizzes last quarter, so I think I was confident in answering these types of questions. 

:::
